CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231107141454_Init') THEN
    CREATE TABLE "Emotions" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "IsCoreEmotion" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Emotions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231107141454_Init') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20231107141454_Init', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231206182706_AddIdentity') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231206182706_AddIdentity') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231206182706_AddIdentity') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231206182706_AddIdentity') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231206182706_AddIdentity') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231206182706_AddIdentity') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231206182706_AddIdentity') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231206182706_AddIdentity') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231206182706_AddIdentity') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231206182706_AddIdentity') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231206182706_AddIdentity') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231206182706_AddIdentity') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231206182706_AddIdentity') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231206182706_AddIdentity') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231206182706_AddIdentity') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20231206182706_AddIdentity', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231209083122_AddsAppRole') THEN
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('0794c54b-7b02-415d-a267-6a9c21b39bd3', NULL, 'Editor', 'EDITOR');
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('2c5e174e-3b0e-446f-86af-483d56fd7210', NULL, 'Administrator', 'ADMINISTRATOR');
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('e738ea63-6593-4098-b0b5-a42c84bfdc66', NULL, 'HeadEditor', 'HEADEDITOR');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231209083122_AddsAppRole') THEN
    INSERT INTO "AspNetUsers" ("Id", "AccessFailedCount", "ConcurrencyStamp", "Email", "EmailConfirmed", "LockoutEnabled", "LockoutEnd", "NormalizedEmail", "NormalizedUserName", "PasswordHash", "PhoneNumber", "PhoneNumberConfirmed", "SecurityStamp", "TwoFactorEnabled", "UserName")
    VALUES ('153dbfe4-1b83-49ce-b7f7-41612d94a150', 0, '0df6785a-e0a3-40d1-a0bc-7a5a113a014e', 'timo_weike@gmx.de', TRUE, FALSE, NULL, 'TIMO_WEIKE@GMX.DE', 'TIMO_WEIKE@GMX.DE', 'AQAAAAIAAYagAAAAEBHi9XJZFbM7BHe5DenM+akwUKWspGnBUx+TJFXOQvVJ1iTNuNMQWyaOQfb3VIejdQ==', NULL, FALSE, '0e8f6c2b-f8fa-4d85-a955-5ad40c656cf6', FALSE, 'timo_weike@gmx.de');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231209083122_AddsAppRole') THEN
    INSERT INTO "AspNetUserRoles" ("RoleId", "UserId")
    VALUES ('2c5e174e-3b0e-446f-86af-483d56fd7210', '153dbfe4-1b83-49ce-b7f7-41612d94a150');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231209083122_AddsAppRole') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20231209083122_AddsAppRole', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240107121859_AddEmotionInfos') THEN
    ALTER TABLE "Emotions" ADD "Color" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240107121859_AddEmotionInfos') THEN
    CREATE TABLE "EmotionDefaultComposePart" (
        "Id" uuid NOT NULL,
        "EmotionId" uuid NOT NULL,
        "PartEmotionId" uuid NOT NULL,
        "PartValue" numeric NOT NULL,
        CONSTRAINT "PK_EmotionDefaultComposePart" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EmotionDefaultComposePart_Emotions_EmotionId" FOREIGN KEY ("EmotionId") REFERENCES "Emotions" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_EmotionDefaultComposePart_Emotions_PartEmotionId" FOREIGN KEY ("PartEmotionId") REFERENCES "Emotions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240107121859_AddEmotionInfos') THEN
    CREATE TABLE "LocalizedEmotionInfo" (
        "Id" uuid NOT NULL,
        "Lcid" text NOT NULL,
        "EmotionId" uuid NOT NULL,
        "LocalizedName" text NOT NULL,
        "LocalizedDesciption" text NOT NULL,
        CONSTRAINT "PK_LocalizedEmotionInfo" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LocalizedEmotionInfo_Emotions_EmotionId" FOREIGN KEY ("EmotionId") REFERENCES "Emotions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240107121859_AddEmotionInfos') THEN
    CREATE TABLE "UserDefinedComposition" (
        "Id" uuid NOT NULL,
        "EmotionId" uuid NOT NULL,
        "PartEmotionId" uuid NOT NULL,
        "PartValue" numeric NOT NULL,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_UserDefinedComposition" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserDefinedComposition_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserDefinedComposition_Emotions_EmotionId" FOREIGN KEY ("EmotionId") REFERENCES "Emotions" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserDefinedComposition_Emotions_PartEmotionId" FOREIGN KEY ("PartEmotionId") REFERENCES "Emotions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240107121859_AddEmotionInfos') THEN
    UPDATE "AspNetUsers" SET "ConcurrencyStamp" = '14078ed8-ee9e-41b7-b702-d8d5a03eeeeb', "SecurityStamp" = 'a91c9c82-e72d-4ac1-894c-40a7dc7ed0e0'
    WHERE "Id" = '153dbfe4-1b83-49ce-b7f7-41612d94a150';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240107121859_AddEmotionInfos') THEN
    CREATE INDEX "IX_EmotionDefaultComposePart_EmotionId" ON "EmotionDefaultComposePart" ("EmotionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240107121859_AddEmotionInfos') THEN
    CREATE INDEX "IX_EmotionDefaultComposePart_PartEmotionId" ON "EmotionDefaultComposePart" ("PartEmotionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240107121859_AddEmotionInfos') THEN
    CREATE INDEX "IX_LocalizedEmotionInfo_EmotionId" ON "LocalizedEmotionInfo" ("EmotionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240107121859_AddEmotionInfos') THEN
    CREATE INDEX "IX_UserDefinedComposition_EmotionId" ON "UserDefinedComposition" ("EmotionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240107121859_AddEmotionInfos') THEN
    CREATE INDEX "IX_UserDefinedComposition_PartEmotionId" ON "UserDefinedComposition" ("PartEmotionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240107121859_AddEmotionInfos') THEN
    CREATE INDEX "IX_UserDefinedComposition_UserId" ON "UserDefinedComposition" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240107121859_AddEmotionInfos') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240107121859_AddEmotionInfos', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240107124154_MakesLocalizedInfosUnique') THEN
    DROP INDEX "IX_LocalizedEmotionInfo_EmotionId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240107124154_MakesLocalizedInfosUnique') THEN
    UPDATE "AspNetUsers" SET "ConcurrencyStamp" = 'e36014bf-7df1-46e6-9001-445fe4bacc9d', "SecurityStamp" = 'fdf2d07a-0e0f-4f7e-995b-d6e13bdcc145'
    WHERE "Id" = '153dbfe4-1b83-49ce-b7f7-41612d94a150';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240107124154_MakesLocalizedInfosUnique') THEN
    CREATE UNIQUE INDEX "IX_LocalizedEmotionInfo_EmotionId_Lcid" ON "LocalizedEmotionInfo" ("EmotionId", "Lcid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240107124154_MakesLocalizedInfosUnique') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240107124154_MakesLocalizedInfosUnique', '8.0.0');
    END IF;
END $EF$;
COMMIT;

