version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: src\Backend\Dockerfile
      target: final
    ports:
      - 8080:80
    depends_on:
      database:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    build:
      context: .
      dockerfile: src\Database\Dockerfile
      target: final
    depends_on:
      database:
        condition: service_healthy
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      PGPASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: mapoffeel # The PostgreSQL default database (automatically created at first launch)

  database:
    # Official Postgres image from DockerHub (we use the last version)
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: mapoffeel # The PostgreSQL default database (automatically created at first launch)
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    name: mof_backend_db
